
# prometheus.yml
global:
    scrape_interval: 5s
    external_labels:
        monitor: 'my-monitor'
scrape_configs:
    - job_name: 'prometheus'
      target_groups:
          - targets: ['localhost:9090']
    - job_name: 'node-exporter'
      target_groups:
          - targets: ['node-exporter:9100']
    - job_name: 'postgresql'
      target_groups:
          - targets: ['postgres-exporter:9187']
    - job_name: 'ngnix'
      target_groups:
          - targets: ['nginx-exporter:9113']
rule_files:
    - 'alert.rules'